// ==UserScript==
// @name        WebPlay for ytdl
// @namespace   Hill98
// @description Show WebPlay play button on some ytdl protocol supported pages
// @version     1.1.0
// @author      Hill-98
// @license     MIT
// @icon        https://www.google.com/s2/favicons?domain=mpv.io
// @downloadURL https://github.com/Hill-98/userscripts/raw/main/webplay-ytdl.user.js
// @homepageURL https://github.com/Hill-98/userscripts
// @supportURL  https://github.com/Hill-98/userscripts/issues
// @updateURL   https://github.com/Hill-98/userscripts/raw/main/webplay-ytdl.user.js
// @grant       none
// @match *://0000.studio/*
// @match *://17.live/*
// @match *://www.1news.co.nz/*
// @match *://www.onenews.co.nz/*
// @match *://www.1tv.ru/*
// @match *://www.20min.ch/*
// @match *://video.twentythree.net/*
// @match *://bonnier-publications-danmark.23video.com/*
// @match *://247sports.com/*
// @match *://24tv.ua/*
// @match *://www.24video.net/*
// @match *://www.24video.me/*
// @match *://www.24video.tube/*
// @match *://www.24video.site/*
// @match *://porno.24video.net/*
// @match *://www.24video.vip/*
// @match *://porn.24video.net/*
// @match *://playout.3qsdn.com/*
// @match *://www.3sat.de/*
// @match *://www.4tube.com/*
// @match *://m.4tube.com/*
// @match *://www.56.com/*
// @match *://www.6play.fr/*
// @match *://www.rtlplay.be/*
// @match *://play.rtl.hr/*
// @match *://www.rtlmost.hu/*
// @match *://7plus.com.au/*
// @match *://8tracks.com/*
// @match *://91porn.com/*
// @match *://9gag.com/*
// @match *://www.9now.com.au/*
// @match *://www.abc.net.au/*
// @match *://iview.abc.net.au/*
// @match *://abcnews.go.com/*
// @match *://abc7news.com/*
// @match *://6abc.com/*
// @match *://clips.abcotvs.com/*
// @match *://abema.tv/*
// @match *://academicearth.org/*
// @match *://www.acast.com/*
// @match *://embed.acast.com/*
// @match *://play.acast.com/*
// @match *://www.acfun.cn/*
// @match *://animationdigitalnetwork.fr/*
// @match *://animedigitalnetwork.fr/*
// @match *://tv.adobe.com/*
// @match *://video.tv.adobe.com/*
// @match *://adultswim.com/*
// @match *://www.adultswim.com/*
// @match *://www.history.com/*
// @match *://www.aetv.com/*
// @match *://www.fyi.tv/*
// @match *://www.mylifetime.com/*
// @match *://watch.lifetimemovieclub.com/*
// @match *://play.aetv.com/*
// @match *://watch.historyvault.com/*
// @match *://www.historyvault.com/*
// @match *://aeon.co/*
// @match *://live.afreecatv.com:8079/*
// @match *://afbbs.afreecatv.com:8080/*
// @match *://vod.afreecatv.com/*
// @match *://www.afreecatv.com/*
// @match *://play.afreecatv.com/*
// @match *://play.afreeca.com/*
// @match *://bj.afreecatv.com/*
// @match *://air.mozilla.org/*
// @match *://www.air.tv/*
// @match *://aitube.kz/*
// @match *://live.aliexpress.com/*
// @match *://balkans.aljazeera.net/*
// @match *://www.allocine.fr/*
// @match *://www.alphaporno.com/*
// @match *://www.alsace20.tv/*
// @match *://cursos.alura.com.br/*
// @match *://amara.org/*
// @match *://www.amazon.in/*
// @match *://www.amazon.com/*
// @match *://www.amazon.co.uk/*
// @match *://www.amazon.es/*
// @match *://www.bbcamerica.com/*
// @match *://www.amc.com/*
// @match *://www.wetv.com/*
// @match *://www.ifc.com/*
// @match *://www.sundancetv.com/*
// @match *://www.americastestkitchen.com/*
// @match *://www.ahctv.com/*
// @match *://anderetijden.nl/*
// @match *://www.angel.com/*
// @match *://www.animalplanet.com/*
// @match *://www.ant1news.gr/*
// @match *://ant1news.gr/*
// @match *://www.antenna.gr/*
// @match *://www.aol.com/*
// @match *://www.aol.ca/*
// @match *://www.aol.co.uk/*
// @match *://www.aol.de/*
// @match *://www.aol.jp/*
// @match *://uvp.apa.at/*
// @match *://uvp-apapublisher.sf.apa.at/*
// @match *://uvp-rma.sf.apa.at/*
// @match *://uvp-kleinezeitung.sf.apa.at/*
// @match *://www.aparat.com/*
// @match *://itunes.apple.com/*
// @match *://ent.appledaily.com.tw/*
// @match *://www.appledaily.com.tw/*
// @match *://podcasts.apple.com/*
// @match *://trailers.apple.com/*
// @match *://movietrailers.apple.com/*
// @match *://archive.org/*
// @match *://www.daserste.de/*
// @match *://www.ardmediathek.de/*
// @match *://one.ard.de/*
// @match *://mediathek.daserste.de/*
// @match *://mediathek.rbb-online.de/*
// @match *://classic.ardmediathek.de/*
// @match *://beta.ardmediathek.de/*
// @match *://ardmediathek.de/*
// @match *://video.qbrick.com/*
// @match *://play.arkena.com/*
// @match *://video.arkena.com/*
// @match *://arte.sky.it/*
// @match *://www.arte.tv/*
// @match *://api.arte.tv/*
// @match *://www.asiancrush.com/*
// @match *://www.yuyutv.com/*
// @match *://www.midnightpulp.com/*
// @match *://www.cocoro.tv/*
// @match *://www.retrocrush.tv/*
// @match *://www.atresplayer.com/*
// @match *://atscaleconference.com/*
// @match *://techchannel.att.com/*
// @match *://www.atv.at/*
// @match *://www.audi-mediacenter.com/*
// @match *://audioboom.com/*
// @match *://nokiatune.audiodraft.com/*
// @match *://vikinggrace.audiodraft.com/*
// @match *://timferriss.audiodraft.com/*
// @match *://www.audiodraft.com/*
// @match *://www.audiomack.com/*
// @match *://audius.co/*
// @match *://awaan.ae/*
// @match *://dcndigital.ae/*
// @match *://www.dcndigital.ae/*
// @match *://tv.telezueri.ch/*
// @match *://www.telebaern.tv/*
// @match *://v.baidu.com/*
// @match *://banbye.com/*
// @match *://www.b-ch.com/*
// @match *://youtube-dl.bandcamp.com/*
// @match *://benprunty.bandcamp.com/*
// @match *://relapsealumni.bandcamp.com/*
// @match *://diskotopia.bandcamp.com/*
// @match *://blazo.bandcamp.com/*
// @match *://nightbringer.bandcamp.com/*
// @match *://jstrecords.bandcamp.com/*
// @match *://insulters.bandcamp.com/*
// @match *://adrianvonziegler.bandcamp.com/*
// @match *://dotscale.bandcamp.com/*
// @match *://nightcallofficial.bandcamp.com/*
// @match *://steviasphere.bandcamp.com/*
// @match *://coldworldofficial.bandcamp.com/*
// @match *://nuclearwarnowproductions.bandcamp.com/*
// @match *://bandcamp.com/*
// @match *://banned.video/*
// @match *://www.bbc.com/*
// @match *://www.bbc.co.uk/*
// @match *://www.bbcnewsd73hkzno2ini43t4gblxvycyac5aw4gnv7t2rccijh7745uqd.onion/*
// @match *://www.bbcweb3hytmzhn5d532owbu6oqadra5z3ar726vq5kgwwn6aucdccrad.onion/*
// @match *://bbv-tv.net/*
// @match *://beatbump.ml/*
// @match *://beatport.com/*
// @match *://beeg.com/*
// @match *://www.behindkink.com/*
// @match *://www.bellator.com/*
// @match *://www.bnnbloomberg.ca/*
// @match *://www.thecomedynetwork.ca/*
// @match *://www.tsn.ca/*
// @match *://www.bnn.ca/*
// @match *://www.ctv.ca/*
// @match *://www.much.com/*
// @match *://www.etalk.ca/*
// @match *://www.cp24.com/*
// @match *://web.arbeitsagentur.de/*
// @match *://www.bet.com/*
// @match *://player.bfi.org.uk/*
// @match *://www.bfmtv.com/*
// @match *://www.bibeltv.de/*
// @match *://www.bigflix.com/*
// @match *://www.bigo.tv/*
// @match *://bigo.tv/*
// @match *://www.bild.de/*
// @match *://www.bilibili.com/*
// @match *://player.bilibili.com/*
// @match *://space.bilibili.com/*
// @match *://www.bilibili.tv/*
// @match *://www.biliintl.com/*
// @match *://bilibili.tv/*
// @match *://live.bilibili.com/*
// @match *://tv.biobiochile.cl/*
// @match *://www.biobiochile.cl/*
// @match *://www.biography.com/*
// @match *://biqle.ru/*
// @match *://biqle.org/*
// @match *://www.bitchute.com/*
// @match *://bitwave.tv/*
// @match *://us-lti.bbcollab.com/*
// @match *://us.bbcollab.com/*
// @match *://ca.bbcollab.com/*
// @match *://eu.bbcollab.com/*
// @match *://au.bbcollab.com/*
// @match *://bleacherreport.com/*
// @match *://www.blogger.com/*
// @match *://www.bloomberg.com/*
// @match *://union.bokecc.com/*
// @match *://de.bongacams.com/*
// @match *://cn.bongacams.com/*
// @match *://de.bongacams.net/*
// @match *://booyah.live/*
// @match *://www.bostonglobe.com/*
// @match *://mlssoccer.app.box.com/*
// @match *://www.bpb.de/*
// @match *://www.br.de/*
// @match *://www.br-klassik.de/*
// @match *://www.bravotv.com/*
// @match *://www.oxygen.com/*
// @match *://www.break.com/*
// @match *://www.breitbart.com/*
// @match *://c.brightcove.com/*
// @match *://link.brightcove.com/*
// @match *://players.brightcove.net/*
// @match *://www.bt.no/*
// @match *://www.bundesliga.com/*
// @match *://uk.businessinsider.com/*
// @match *://www.businessinsider.nl/*
// @match *://www.businessinsider.com/*
// @match *://www.buzzfeed.com/*
// @match *://www.byutv.org/*
// @match *://cableav.tv/*
// @match *://www.callin.com/*
// @match *://cwwp2.dot.ca.gov/*
// @match *://www.cam4.com/*
// @match *://www.camdemy.com/*
// @match *://www.cammodels.com/*
// @match *://www.camsoda.com/*
// @match *://camwithher.tv/*
// @match *://www.canalalpha.ch/*
// @match *://www.canalc2.tv/*
// @match *://archives-canalc2.u-strasbg.fr/*
// @match *://www.mycanal.fr/*
// @match *://www.piwiplus.fr/*
// @match *://mediazone.vrt.be/*
// @match *://www.canvas.be/*
// @match *://www.een.be/*
// @match *://video1.carambatv.ru/*
// @match *://carambatv.ru/*
// @match *://www.cartoonnetwork.com/*
// @match *://www.cbc.ca/*
// @match *://www.cbs.com/*
// @match *://colbertlateshow.com/*
// @match *://www.colbertlateshow.com/*
// @match *://www.cnet.com/*
// @match *://www.zdnet.com/*
// @match *://newyork.cbslocal.com/*
// @match *://losangeles.cbslocal.com/*
// @match *://cleveland.cbslocal.com/*
// @match *://www.cbsnews.com/*
// @match *://www.cbssports.com/*
// @match *://embed.247sports.com/*
// @match *://www.ccma.cat/*
// @match *://sports.cntv.cn/*
// @match *://tv.cctv.com/*
// @match *://english.cntv.cn/*
// @match *://cctv.cntv.cn/*
// @match *://www.ncpa-classic.com/*
// @match *://ent.cntv.cn/*
// @match *://tv.cntv.cn/*
// @match *://www.cda.pl/*
// @match *://ebd.cda.pl/*
// @match *://cellebrite.com/*
// @match *://www.ceskatelevize.cz/*
// @match *://news.cgtn.com/*
// @match *://channel9.msdn.com/*
// @match *://charlierose.com/*
// @match *://www.chaturbate.com/*
// @match *://chaturbate.com/*
// @match *://en.chaturbate.com/*
// @match *://www.chilloutzone.net/*
// @match *://chingari.io/*
// @match *://chirb.it/*
// @match *://chirbit.com/*
// @match *://www.cielotv.it/*
// @match *://player.cinchcast.com/*
// @match *://www.cinemax.com/*
// @match *://www.cinetecamilano.it/*
// @match *://ciscolive.cisco.com/*
// @match *://www.ciscolive.com/*
// @match *://demosubdomain.webex.com/*
// @match *://cjsw.com/*
// @match *://www.cliphunter.com/*
// @match *://www.clippituser.tv/*
// @match *://www.clip.rs/*
// @match *://www.clipsyndicate.com/*
// @match *://chic.clipsyndicate.com/*
// @match *://closertotruth.com/*
// @match *://embed.cloudflarestream.com/*
// @match *://watch.cloudflarestream.com/*
// @match *://cloudflarestream.com/*
// @match *://embed.videodelivery.net/*
// @match *://www.cloudy.ec/*
// @match *://www.clubic.com/*
// @match *://clyp.it/*
// @match *://www.cmt.com/*
// @match *://video.cnbc.com/*
// @match *://www.cnbc.com/*
// @match *://edition.cnn.com/*
// @match *://www.cnn.com/*
// @match *://money.cnn.com/*
// @match *://cnn.com/*
// @match *://reliablesources.blogs.cnn.com/*
// @match *://www.cnnindonesia.com/*
// @match *://www.cc.com/*
// @match *://www.comedycentral.tv/*
// @match *://video.wired.com/*
// @match *://video.gq.com/*
// @match *://player.cnevids.com/*
// @match *://player-backend.cnevids.com/*
// @match *://www.contv.com/*
// @match *://watch.cookingchanneltv.com/*
// @match *://www.hgtv.ca/*
// @match *://www.foodnetwork.ca/*
// @match *://etcanada.com/*
// @match *://www.history.ca/*
// @match *://www.showcase.ca/*
// @match *://www.bigbrothercanada.ca/*
// @match *://www.seriesplus.com/*
// @match *://www.disneychannel.ca/*
// @match *://coub.com/*
// @match *://c-cdn.coub.com/*
// @match *://cozy.tv/*
// @match *://www.cpac.ca/*
// @match *://www.cracked.com/*
// @match *://www.crackle.com/*
// @match *://www.sonycrackle.com/*
// @match *://www.craftsy.com/*
// @match *://embed.crooksandliars.com/*
// @match *://crowdbunker.com/*
// @match *://www.crunchyroll.com/*
// @match *://beta.crunchyroll.com/*
// @match *://www.c-span.org/*
// @match *://news.cts.com.tw/*
// @match *://www.ctvnews.ca/*
// @match *://vancouverisland.ctvnews.ca/*
// @match *://cu.ntv.co.jp/*
// @match *://www.cultureunplugged.com/*
// @match *://app.curiositystream.com/*
// @match *://curiositystream.com/*
// @match *://cwtv.com/*
// @match *://www.cwseed.com/*
// @match *://cwtvpr.com/*
// @match *://app.cybrary.it/*
// @match *://daftsex.com/*
// @match *://dagelijksekost.een.be/*
// @match *://www.dailymail.co.uk/*
// @match *://www.dailymotion.com/*
// @match *://geo.dailymotion.com/*
// @match *://www.lequipe.fr/*
// @match *://www.dailywire.com/*
// @match *://www.clubdam.com/*
// @match *://tvpot.daum.net/*
// @match *://m.tvpot.daum.net/*
// @match *://videofarm.daum.net/*
// @match *://player.daystar.tv/*
// @match *://www.dagbladet.no/*
// @match *://www.dctp.tv/*
// @match *://www.deezer.com/*
// @match *://www.defense.gouv.fr/*
// @match *://www.democracynow.org/*
// @match *://www.destinationamerica.com/*
// @match *://2m.ma/*
// @match *://www.dhm.de/*
// @match *://digg.com/*
// @match *://www.digitalconcerthall.com/*
// @match *://evt.dispeak.com/*
// @match *://events.digitallyspeaking.com/*
// @match *://sevt.dispeak.com/*
// @match *://www.ultimedia.com/*
// @match *://www.digiteka.net/*
// @match *://go.discovery.com/*
// @match *://www.investigationdiscovery.com/*
// @match *://www.sciencechannel.com/*
// @match *://www.discoverylife.com/*
// @match *://www.tlc.de/*
// @match *://www.dmax.de/*
// @match *://www.dplay.co.uk/*
// @match *://tlc.de/*
// @match *://www.discoveryplus.com/*
// @match *://discoveryplus.com/*
// @match *://www.discoveryplus.in/*
// @match *://www.discoveryplus.it/*
// @match *://video.disney.com/*
// @match *://www.starwars.com/*
// @match *://videos.disneylatino.com/*
// @match *://video.en.disneyme.com/*
// @match *://video.disneyturkiye.com.tr/*
// @match *://disneyjunior.disney.com/*
// @match *://spiderman.marvelkids.com/*
// @match *://disneyjunior.en.disneyme.com/*
// @match *://disneychannel.de/*
// @match *://watch.diynetwork.com/*
// @match *://dlive.tv/*
// @match *://dotsub.com/*
// @match *://www.douyin.com/*
// @match *://v.douyu.com/*
// @match *://vmobile.douyu.com/*
// @match *://www.douyutv.com/*
// @match *://www.douyu.com/*
// @match *://www.dplay.se/*
// @match *://www.dplay.dk/*
// @match *://www.dplay.no/*
// @match *://it.dplay.com/*
// @match *://es.dplay.com/*
// @match *://www.dplay.fi/*
// @match *://www.dplay.jp/*
// @match *://www.discoveryplus.se/*
// @match *://www.discoveryplus.dk/*
// @match *://www.discoveryplus.no/*
// @match *://www.discoveryplus.es/*
// @match *://www.discoveryplus.fi/*
// @match *://www.dr.dk/*
// @match *://peacocktv.com/*
// @match *://www.channel4.com/*
// @match *://www.channel5.com/*
// @match *://hsesn.apps.disneyplus.com/*
// @match *://www.disneyplus.com/*
// @match *://open.spotify.com/*
// @match *://www.tvnz.co.nz/*
// @match *://www.oneplus.ch/*
// @match *://www.artstation.com/*
// @match *://www.philo.com/*
// @match *://www.mech-plus.com/*
// @match *://watch.mech-plus.com/*
// @match *://www.aha.video/*
// @match *://mubi.com/*
// @match *://www.vootkids.com/*
// @match *://www.nowtv.it/*
// @match *://tv.apple.com/*
// @match *://drooble.com/*
// @match *://www.dropbox.com/*
// @match *://www.dropout.tv/*
// @match *://www.drtuber.com/*
// @match *://m.drtuber.com/*
// @match *://dr-massive.com/*
// @match *://d.tube/*
// @match *://w.duboku.io/*
// @match *://www.dumpert.nl/*
// @match *://legacy.dumpert.nl/*
// @match *://video.aktualne.cz/*
// @match *://www.dw.com/*
// @match *://lentaru.media.eagleplatform.com/*
// @match *://www.ebaumsworld.com/*
// @match *://www.echo.msk.ru/*
// @match *://egghead.io/*
// @match *://app.egghead.io/*
// @match *://www.ehftv.com/*
// @match *://www.ehow.com/*
// @match *://1und1.tv/*
// @match *://einthusan.tv/*
// @match *://einthusan.com/*
// @match *://einthusan.ca/*
// @match *://www.eitb.tv/*
// @match *://api-prod.ellentube.com/*
// @match *://www.ellentube.com/*
// @match *://elonet.finna.fi/*
// @match *://blogs.elpais.com/*
// @match *://elcomidista.elpais.com/*
// @match *://elpais.com/*
// @match *://epv.elpais.com/*
// @match *://cdn.embedly.com/*
// @match *://www.empflix.com/*
// @match *://www.engadget.com/*
// @match *://www.epicon.in/*
// @match *://www.theepochtimes.com/*
// @match *://www.eporner.com/*
// @match *://www.eroprofile.com/*
// @match *://www.ertflix.gr/*
// @match *://www.ert.gr/*
// @match *://www.escapistmagazine.com/*
// @match *://escapistmagazine.com/*
// @match *://v1.escapistmagazine.com/*
// @match *://espn.go.com/*
// @match *://broadband.espn.go.com/*
// @match *://nonredline.sports.espn.go.com/*
// @match *://cdn.espn.go.com/*
// @match *://www.espn.com/*
// @match *://www.espnfc.us/*
// @match *://www.espnfc.com/*
// @match *://www.espncricinfo.com/*
// @match *://video.esri.com/*
// @match *://ec.europa.eu/*
// @match *://multimedia.europarl.europa.eu/*
// @match *://webstreaming.europarl.europa.eu/*
// @match *://www.europeantour.com/*
// @match *://www.eurosport.com/*
// @match *://euscreen.eu/*
// @match *://tvonline.ewe.de/*
// @match *://www.expotv.com/*
// @match *://www.expressen.se/*
// @match *://www.di.se/*
// @match *://www.extremetube.com/*
// @match *://www.eyedo.tv/*
// @match *://www.facebook.com/*
// @match *://m.facebook.com/*
// @match *://zh-hk.facebook.com/*
// @match *://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/*
// @match *://fancode.com/*
// @match *://www.faz.net/*
// @match *://video.fc2.com/*
// @match *://live.fc2.com/*
// @match *://fc-zenit.ru/*
// @match *://www.fifa.com/*
// @match *://www.filmmodu.org/*
// @match *://www.filmon.com/*
// @match *://www.filmweb.no/*
// @match *://fivethirtyeight.com/*
// @match *://5-tv.ru/*
// @match *://www.5-tv.ru/*
// @match *://www.flickr.com/*
// @match *://www.ft.dk/*
// @match *://watch.foodnetwork.com/*
// @match *://footyroom.com/*
// @match *://www.formula1.com/*
// @match *://www.fox.com/*
// @match *://www.fox9.com/*
// @match *://foxgay.com/*
// @match *://video.foxnews.com/*
// @match *://video.foxbusiness.com/*
// @match *://video.insider.foxnews.com/*
// @match *://www.foxnews.com/*
// @match *://insider.foxnews.com/*
// @match *://www.foxsports.com/*
// @match *://fptplay.vn/*
// @match *://www.radiofrance.fr/*
// @match *://www.franceinter.fr/*
// @match *://sivideo.webservices.francetelevisions.fr/*
// @match *://videos.francetv.fr/*
// @match *://www.francetvinfo.fr/*
// @match *://france3-regions.francetvinfo.fr/*
// @match *://www.france.tv/*
// @match *://mobile.france.tv/*
// @match *://www.freesound.org/*
// @match *://www.freespeech.org/*
// @match *://www.freetv.com/*
// @match *://api.frontendmasters.com/*
// @match *://frontendmasters.com/*
// @match *://fod.fujitv.co.jp/*
// @match *://www.funimation.com/*
// @match *://www.funimationnow.uk/*
// @match *://www.funk.net/*
// @match *://fusion.tv/*
// @match *://www.fux.com/*
// @match *://www.fuyin.tv/*
// @match *://gab.com/*
// @match *://tv.gab.com/*
// @match *://www.gaia.com/*
// @match *://www.gameinformer.com/*
// @match *://gamejolt.com/*
// @match *://www.gamespot.com/*
// @match *://www.gamestar.de/*
// @match *://www.gamepro.de/*
// @match *://www.gaskrank.tv/*
// @match *://www.gazeta.ru/*
// @match *://www.gdcvault.com/*
// @match *://gdcvault.com/*
// @match *://video.lastampa.it/*
// @match *://video.huffingtonpost.it/*
// @match *://video.espresso.repubblica.it/*
// @match *://video.repubblica.it/*
// @match *://video.ilsecoloxix.it/*
// @match *://video.iltirreno.gelocal.it/*
// @match *://video.messaggeroveneto.gelocal.it/*
// @match *://video.ilpiccolo.gelocal.it/*
// @match *://video.gazzettadimantova.gelocal.it/*
// @match *://video.mattinopadova.gelocal.it/*
// @match *://video.laprovinciapavese.gelocal.it/*
// @match *://video.tribunatreviso.gelocal.it/*
// @match *://video.nuovavenezia.gelocal.it/*
// @match *://video.gazzettadimodena.gelocal.it/*
// @match *://video.lanuovaferrara.gelocal.it/*
// @match *://video.corrierealpi.gelocal.it/*
// @match *://video.lasentinella.gelocal.it/*
// @match *://gem.cbc.ca/*
// @match *://genius.com/*
// @match *://www.gettr.com/*
// @match *://gettr.com/*
// @match *://gfycat.com/*
// @match *://thumbs.gfycat.com/*
// @match *://giant.gfycat.com/*
// @match *://www.giantbomb.com/*
// @match *://www.giga.de/*
// @match *://iptv.glattvision.ch/*
// @match *://share.glide.me/*
// @match *://g1.globo.com/*
// @match *://globoplay.globo.com/*
// @match *://canalbrasil.globo.com/*
// @match *://globosatplay.globo.com/*
// @match *://globotv.globo.com/*
// @match *://canaloff.globo.com/*
// @match *://gq.globo.com/*
// @match *://gshow.globo.com/*
// @match *://oglobo.globo.com/*
// @match *://ge.globo.com/*
// @match *://redeglobo.globo.com/*
// @match *://video.glomex.com/*
// @match *://player.glomex.com/*
// @match *://abc.go.com/*
// @match *://disneynow.com/*
// @match *://freeform.go.com/*
// @match *://abc.com/*
// @match *://fxnow.fxnetworks.com/*
// @match *://disneynow.go.com/*
// @match *://www.freeform.com/*
// @match *://discovery.com/*
// @match *://www.godtube.com/*
// @match *://gofile.io/*
// @match *://video.golem.de/*
// @match *://goodgame.ru/*
// @match *://podcasts.google.com/*
// @match *://drive.google.com/*
// @match *://www.goplay.be/*
// @match *://gopro.com/*
// @match *://www.goshgay.com/*
// @match *://www.gotostage.com/*
// @match *://on-demand.gputechconf.com/*
// @match *://gronkh.tv/*
// @match *://www.groupon.com/*
// @match *://www.harpodeon.com/*
// @match *://www.hbo.com/*
// @match *://hearthis.at/*
// @match *://www.heise.de/*
// @match *://hellporno.com/*
// @match *://hellporno.net/*
// @match *://video.helsinki.fi/*
// @match *://hentai.animestigma.com/*
// @match *://hetklokhuis.nl/*
// @match *://www.hgtv.com/*
// @match *://de.hgtv.com/*
// @match *://watch.hgtv.com/*
// @match *://www.hidive.com/*
// @match *://www.historicfilms.com/*
// @match *://link.theplatform.com/*
// @match *://player.theplatform.com/*
// @match *://www.hitbox.tv/*
// @match *://www.smashcast.tv/*
// @match *://hitrecord.org/*
// @match *://www.hkedcity.net/*
// @match *://holodex.net/*
// @match *://staging.holodex.net/*
// @match *://www.hotnewhiphop.com/*
// @match *://www.hotstar.com/*
// @match *://www.howcast.com/*
// @match *://www.stufftoblowyourmind.com/*
// @match *://shows.howstuffworks.com/*
// @match *://www.hessenschau.de/*
// @match *://www.hr-fernsehen.de/*
// @match *://hrti.hrt.hr/*
// @match *://www.hse.de/*
// @match *://www.huajiao.com/*
// @match *://live.huffingtonpost.com/*
// @match *://www.hungama.com/*
// @match *://hypem.com/*
// @match *://hytale.com/*
// @match *://www.hytale.com/*
// @match *://www.helsinkikanava.fi/*
// @match *://suite.icareus.com/*
// @match *://asahitv.fi/*
// @match *://hyvinvointitv.fi/*
// @match *://inez.fi/*
// @match *://www.permanto.fi/*
// @match *://videos.minifiddlers.org/*
// @match *://www.iflix.com/*
// @match *://www.ign.com/*
// @match *://www.pcmag.com/*
// @match *://me.ign.com/*
// @match *://adria.ign.com/*
// @match *://kr.ign.com/*
// @match *://www.iheart.com/*
// @match *://www.iheartpodcastnetwork.com/*
// @match *://www.iltalehti.fi/*
// @match *://www.imdb.com/*
// @match *://i.imgur.com/*
// @match *://imgur.com/*
// @match *://www.ina.fr/*
// @match *://m.ina.fr/*
// @match *://www.inc.com/*
// @match *://indavideo.hu/*
// @match *://embed.indavideo.hu/*
// @match *://assets.indavideo.hu/*
// @match *://www.infoq.com/*
// @match *://instagram.com/*
// @match *://www.instagram.com/*
// @match *://www.internazionale.it/*
// @match *://video.internetvideoarchive.net/*
// @match *://prima.iprima.cz/*
// @match *://play.iprima.cz/*
// @match *://www.iprima.cz/*
// @match *://zoom.iprima.cz/*
// @match *://krimi.iprima.cz/*
// @match *://cool.iprima.cz/*
// @match *://love.iprima.cz/*
// @match *://cnn.iprima.cz/*
// @match *://www.iq.com/*
// @match *://www.iqiyi.com/*
// @match *://yule.iqiyi.com/*
// @match *://www.pps.tv/*
// @match *://watch.islamchannel.tv/*
// @match *://www.israelnationalnews.com/*
// @match *://app.itpro.tv/*
// @match *://tv.ittf.com/*
// @match *://www.itv.com/*
// @match *://www.ivi.ru/*
// @match *://www.ivi.tv/*
// @match *://www.ivideon.com/*
// @match *://iwara.tv/*
// @match *://ecchi.iwara.tv/*
// @match *://www.iwara.tv/*
// @match *://www.ixigua.com/*
// @match *://www.izlesene.com/*
// @match *://jable.tv/*
// @match *://www.jamendo.com/*
// @match *://licensing.jamendo.com/*
// @match *://www.jeuxvideo.com/*
// @match *://media.joj.sk/*
// @match *://www.jove.com/*
// @match *://content.jwplatform.com/*
// @match *://cdn.jwplayer.com/*
// @match *://tv.kakao.com/*
// @match *://www.kaltura.com/*
// @match *://cdnapisec.kaltura.com/*
// @match *://www.kaltura.com:443/*
// @match *://kanal2.postimees.ee/*
// @match *://www.kankanews.com/*
// @match *://www.karaoketv.co.il/*
// @match *://www.karrierevideos.at/*
// @match *://www.mtv.fi/*
// @match *://www.katsomo.fi/*
// @match *://www.mtvuutiset.fi/*
// @match *://www.keezmovies.com/*
// @match *://members.kelbyone.com/*
// @match *://www.ketnet.be/*
// @match *://www.khanacademy.org/*
// @match *://kick.com/*
// @match *://www.kicker.de/*
// @match *://www.kickstarter.com/*
// @match *://kinja.com/*
// @match *://www.kinopoisk.ru/*
// @match *://video.kompas.com/*
// @match *://www.konserthusetplay.se/*
// @match *://rspoplay.se/*
// @match *://www.kooapp.com/*
// @match *://krasview.ru/*
// @match *://play.kth.se/*
// @match *://v.ku6.com/*
// @match *://www.kusi.com/*
// @match *://kusi.com/*
// @match *://www.kuwo.cn/*
// @match *://yinyue.kuwo.cn/*
// @match *://www.la7.it/*
// @match *://www.laola1.tv/*
// @match *://www.last.fm/*
// @match *://lbry.tv/*
// @match *://odysee.com/*
// @match *://www.tf1info.fr/*
// @match *://www.lci.fr/*
// @match *://www.lcp.fr/*
// @match *://play.lcp.fr/*
// @match *://www.le.com/*
// @match *://sports.le.com/*
// @match *://www.lesports.com/*
// @match *://lecture2go.uni-hamburg.de/*
// @match *://app.lecturio.com/*
// @match *://www.lecturio.de/*
// @match *://www.lego.com/*
// @match *://www.lemonde.fr/*
// @match *://redaction.actu.lemonde.fr/*
// @match *://lenta.ru/*
// @match *://tv.le.com/*
// @match *://list.le.com/*
// @match *://yuntv.letv.com/*
// @match *://html5-player.libsyn.com/*
// @match *://life.ru/*
// @match *://embed.life.ru/*
// @match *://likee.video/*
// @match *://www.likee.video/*
// @match *://link.videoplatform.limelight.com/*
// @match *://assets.delvenetworks.com/*
// @match *://live.line.me/*
// @match *://www.linkedin.com/*
// @match *://linuxacademy.com/*
// @match *://www.liputan6.com/*
// @match *://www.listennotes.com/*
// @match *://www.litv.tv/*
// @match *://andrei-bt.livejournal.com/*
// @match *://new.livestream.com/*
// @match *://livestream.com/*
// @match *://original.livestream.com/*
// @match *://livestreamfails.com/*
// @match *://lnk.lt/*
// @match *://www.lnkgo.lt/*
// @match *://lnkgo.alfa.lt/*
// @match *://loc.gov/*
// @match *://www.loc.gov/*
// @match *://www.localnews8.com/*
// @match *://lovehomeporn.com/*
// @match *://www.lrt.lt/*
// @match *://www.lynda.com/*
// @match *://educourse.ga/*
// @match *://www.m6.fr/*
// @match *://www.magenta-musik-360.de/*
// @match *://my.mail.ru/*
// @match *://m.my.mail.ru/*
// @match *://videoapi.my.mail.ru/*
// @match *://webtools-e18da6642b684f8aa9ae449862783a56.msvdn.net/*
// @match *://webtools-859c1818ed614cc5b0047439470927b0.msvdn.net/*
// @match *://webtools-f5842579ff984c1c98d63b8d789673eb.msvdn.net/*
// @match *://f5842579ff984c1c98d63b8d789673eb.msvdn.net/*
// @match *://webtools.msvdn.net/*
// @match *://859c1818ed614cc5b0047439470927b0.msvdn.net/*
// @match *://www.mall.tv/*
// @match *://sk.mall.tv/*
// @match *://www.mgtv.com/*
// @match *://w.mgtv.com/*
// @match *://www.manototv.com/*
// @match *://www.manyvids.com/*
// @match *://www.maoritelevision.com/*
// @match *://videoarchiv.markiza.sk/*
// @match *://www.markiza.sk/*
// @match *://dajto.markiza.sk/*
// @match *://superstar.markiza.sk/*
// @match *://hybsa.markiza.sk/*
// @match *://doma.markiza.sk/*
// @match *://www.tvnoviny.sk/*
// @match *://massengeschmack.tv/*
// @match *://www.masters.com/*
// @match *://matchtv.ru/*
// @match *://www.mdr.de/*
// @match *://www.kika.de/*
// @match *://medal.tv/*
// @match *://media.ccc.de/*
// @match *://www.mediaite.com/*
// @match *://mediaklikk.hu/*
// @match *://m4sport.hu/*
// @match *://hirado.hu/*
// @match *://petofilive.hu/*
// @match *://www.bndestem.nl/*
// @match *://www.gelderlander.nl/*
// @match *://embed.mychannels.video/*
// @match *://mychannels.video/*
// @match *://mediasetinfinity.mediaset.it/*
// @match *://www.mediasetplay.mediaset.it/*
// @match *://static3.mediasetplay.mediaset.it/*
// @match *://hitsmediaweb.h-its.org/*
// @match *://mediasite.uib.no/*
// @match *://collegerama.tudelft.nl/*
// @match *://digitalops.sandia.gov/*
// @match *://mediasite.ntnu.no/*
// @match *://events7.mediasite.com/*
// @match *://medaudio.medicine.iu.edu/*
// @match *://uipsyc.mediasite.com/*
// @match *://live.libraries.psu.edu/*
// @match *://msite.misis.ru/*
// @match *://mdstrm.com/*
// @match *://vodupload-api.mediaworks.nz/*
// @match *://www.medici.tv/*
// @match *://player.megaphone.fm/*
// @match *://www.megatv.com/*
// @match *://www.meipai.com/*
// @match *://vod.melon.com/*
// @match *://video.meta.ua/*
// @match *://metacafe.com/*
// @match *://www.metacafe.com/*
// @match *://www.metacritic.com/*
// @match *://www.mewatch.sg/*
// @match *://live.mewatch.sg/*
// @match *://m.mgoon.com/*
// @match *://www.mgoon.com/*
// @match *://video.mgoon.com/*
// @match *://www.miaopai.com/*
// @match *://www.microsoft.com/*
// @match *://web.microsoftstream.com/*
// @match *://msit.microsoftstream.com/*
// @match *://www.mildom.com/*
// @match *://www.minds.com/*
// @match *://www.ministrygrid.com/*
// @match *://www.miomio.tv/*
// @match *://www.mirrativ.com/*
// @match *://www.mirror.co.uk/*
// @match *://www.mitele.es/*
// @match *://mixch.tv/*
// @match *://www.mixcloud.com/*
// @match *://beta.mixcloud.com/*
// @match *://www.mlb.com/*
// @match *://m.mlb.com/*
// @match *://mlb.mlb.com/*
// @match *://www.mlssoccer.com/*
// @match *://www.whitecapsfc.com/*
// @match *://www.torontofc.ca/*
// @match *://www.sportingkc.com/*
// @match *://www.soundersfc.com/*
// @match *://www.sjearthquakes.com/*
// @match *://www.rsl.com/*
// @match *://www.timbers.com/*
// @match *://www.philadelphiaunion.com/*
// @match *://www.orlandocitysc.com/*
// @match *://www.newyorkredbulls.com/*
// @match *://www.nycfc.com/*
// @match *://www.revolutionsoccer.net/*
// @match *://www.nashvillesc.com/*
// @match *://www.cfmontreal.com/*
// @match *://www.intermiamicf.com/*
// @match *://www.lagalaxy.com/*
// @match *://www.lafc.com/*
// @match *://www.houstondynamofc.com/*
// @match *://www.dcunited.com/*
// @match *://www.fcdallas.com/*
// @match *://www.columbuscrew.com/*
// @match *://www.coloradorapids.com/*
// @match *://www.fccincinnati.com/*
// @match *://www.chicagofirefc.com/*
// @match *://www.austinfc.com/*
// @match *://www.atlutd.com/*
// @match *://www.mnet.com/*
// @match *://mnet.interest.me/*
// @match *://tvplus.m-net.de/*
// @match *://video.mocha.com.vn/*
// @match *://moevideo.net/*
// @match *://playreplay.net/*
// @match *://www.mofosex.com/*
// @match *://www.mojvideo.com/*
// @match *://www.morningstar.com/*
// @match *://news.morningstar.com/*
// @match *://motherless.com/*
// @match *://www.motorsport.com/*
// @match *://watch.motortrend.com/*
// @match *://www.motortrendondemand.com/*
// @match *://www.movieclips.com/*
// @match *://www.moviefap.com/*
// @match *://www.moviepilot.de/*
// @match *://www.moview.id/*
// @match *://www.moviezine.se/*
// @match *://movingimage.nls.uk/*
// @match *://www.msn.com/*
// @match *://www.tvplay.lv/*
// @match *://play.tv3.lt/*
// @match *://www.tv3play.ee/*
// @match *://www.tv3play.se/*
// @match *://www.tv6play.se/*
// @match *://www.tv8play.se/*
// @match *://www.tv3play.no/*
// @match *://www.viasat4play.no/*
// @match *://www.tv6play.no/*
// @match *://play.novatv.bg/*
// @match *://play.nova.bg/*
// @match *://tvplay.skaties.lv/*
// @match *://tv3play.tv3.ee/*
// @match *://www.mtv.com/*
// @match *://www.mtv.de/*
// @match *://www.mtv.it/*
// @match *://www.mtvjapan.com/*
// @match *://media.mtvnservices.com/*
// @match *://www.muenchen.tv/*
// @match *://murrtube.net/*
// @match *://musescore.com/*
// @match *://www.musicdex.org/*
// @match *://mva.microsoft.com/*
// @match *://www.microsoftvirtualacademy.com/*
// @match *://mwave.interest.me/*
// @match *://www.mxplayer.in/*
// @match *://mychannels.com/*
// @match *://myspace.com/*
// @match *://www.myspass.de/*
// @match *://myvi.ru/*
// @match *://myvi.tv/*
// @match *://www.myvi.ru/*
// @match *://www.myvideo.ge/*
// @match *://www.myvidster.com/*
// @match *://www.myvi.tv/*
// @match *://www.n-tv.de/*
// @match *://rs.n1info.com/*
// @match *://n1info.si/*
// @match *://ba.n1info.com/*
// @match *://nova.rs/*
// @match *://hr.n1info.com/*
// @match *://best-vod.umn.cdn.united.cloud/*
// @match *://tv.nate.com/*
// @match *://video.nationalgeographic.com/*
// @match *://www.nationalgeographic.com/*
// @match *://tv.naver.com/*
// @match *://tvcast.naver.com/*
// @match *://now.naver.com/*
// @match *://www.nba.com/*
// @match *://watch.nba.com/*
// @match *://secure.nba.com/*
// @match *://www.nbc.com/*
// @match *://www.nbcnews.com/*
// @match *://www.today.com/*
// @match *://www.msnbc.com/*
// @match *://www.nbcolympics.com/*
// @match *://stream.nbcolympics.com/*
// @match *://www.nbcsports.com/*
// @match *://stream.nbcsports.com/*
// @match *://vplayer.nbcsports.com/*
// @match *://www.nbclosangeles.com/*
// @match *://www.telemundoarizona.com/*
// @match *://www.ndr.de/*
// @match *://khabar.ndtv.com/*
// @match *://movies.ndtv.com/*
// @match *://www.ndtv.com/*
// @match *://auto.ndtv.com/*
// @match *://sports.ndtv.com/*
// @match *://gadgets.ndtv.com/*
// @match *://profit.ndtv.com/*
// @match *://food.ndtv.com/*
// @match *://doctor.ndtv.com/*
// @match *://swirlster.ndtv.com/*
// @match *://nebula.app/*
// @match *://watchnebula.com/*
// @match *://www.nerdcubed.co.uk/*
// @match *://music.163.com/*
// @match *://y.music.163.com/*
// @match *://netplus.tv/*
// @match *://www.netverse.id/*
// @match *://netverse.id/*
// @match *://www.netzkino.de/*
// @match *://www.newgrounds.com/*
// @match *://burn7.newgrounds.com/*
// @match *://brian-beaton.newgrounds.com/*
// @match *://newspicks.com/*
// @match *://www.newstube.ru/*
// @match *://www.newsy.com/*
// @match *://hk.apple.nextmedia.com/*
// @match *://hk.dv.nextmedia.com/*
// @match *://www.nexttv.com.tw/*
// @match *://api.nexx.cloud/*
// @match *://api.nexxcdn.com/*
// @match *://arc.nexx.cloud/*
// @match *://embed.nexx.cloud/*
// @match *://www.nfb.ca/*
// @match *://www.nfhsnetwork.com/*
// @match *://www.nfl.com/*
// @match *://www.chiefs.com/*
// @match *://www.buffalobills.com/*
// @match *://www.raiders.com/*
// @match *://www2.nhk.or.jp/*
// @match *://www.nhk.or.jp/*
// @match *://www3.nhk.or.jp/*
// @match *://www.nhl.com/*
// @match *://www.wch2016.com/*
// @match *://www.nick.com/*
// @match *://www.nickjr.com/*
// @match *://www.nick.de/*
// @match *://www.nickelodeon.nl/*
// @match *://www.nickelodeon.at/*
// @match *://www.nick.com.pl/*
// @match *://www.nickelodeon.no/*
// @match *://www.nickelodeon.dk/*
// @match *://www.nickelodeon.se/*
// @match *://www.nick.ch/*
// @match *://www.nickelodeon.be/*
// @match *://www.nickjr.com.br/*
// @match *://mundonick.uol.com.br/*
// @match *://www.nickjr.nl/*
// @match *://www.nickjr.de/*
// @match *://www.nickelodeonjunior.fr/*
// @match *://www.nickelodeon.ru/*
// @match *://www.nickelodeon.fr/*
// @match *://www.nickelodeon.es/*
// @match *://www.nickelodeon.pt/*
// @match *://www.nickelodeon.ro/*
// @match *://www.nickelodeon.hu/*
// @match *://www.nickelodeon.com.tr/*
// @match *://www.nicknight.at/*
// @match *://www.nicovideo.jp/*
// @match *://sp.nicovideo.jp/*
// @match *://nico.ms/*
// @match *://www.nintendo.com/*
// @match *://de.nttr.stream/*
// @match *://www.n-joy.de/*
// @match *://njpwworld.com/*
// @match *://front.njpwworld.com/*
// @match *://www.nobelprize.org/*
// @match *://open.noice.id/*
// @match *://www.nonktube.com/*
// @match *://adult.noodlemagazine.com/*
// @match *://noovo.ca/*
// @match *://normalboots.com/*
// @match *://nos.nl/*
// @match *://nosvideo.com/*
// @match *://tn.nova.cz/*
// @match *://fanda.nova.cz/*
// @match *://novaplus.nova.cz/*
// @match *://sport.tn.nova.cz/*
// @match *://doma.nova.cz/*
// @match *://prask.nova.cz/*
// @match *://tv.nova.cz/*
// @match *://media.cms.nova.cz/*
// @match *://www.nowness.com/*
// @match *://cn.nowness.com/*
// @match *://www.noz.de/*
// @match *://www.npo.nl/*
// @match *://www.ntr.nl/*
// @match *://www.omroepwnl.nl/*
// @match *://www.zapp.nl/*
// @match *://www.npo3.nl/*
// @match *://www.npostart.nl/*
// @match *://npo.nl/*
// @match *://www.npr.org/*
// @match *://www.nrk.no/*
// @match *://v8-psapi.nrk.no/*
// @match *://radio.nrk.no/*
// @match *://tv.nrk.no/*
// @match *://tv.nrksuper.no/*
// @match *://nrksuper.no/*
// @match *://www.nrl.com/*
// @match *://www.ntv.ru/*
// @match *://www.nuvid.com/*
// @match *://m.nuvid.com/*
// @match *://www.nytimes.com/*
// @match *://cooking.nytimes.com/*
// @match *://www.nzherald.co.nz/*
// @match *://nzherald.co.nz/*
// @match *://www.nzz.ch/*
// @match *://ocw.mit.edu/*
// @match *://odatv.com/*
// @match *://ok.ru/*
// @match *://m.ok.ru/*
// @match *://www.ok.ru/*
// @match *://mobile.ok.ru/*
// @match *://of.tv/*
// @match *://www.oktoberfest-tv.de/*
// @match *://olympics.com/*
// @match *://event.on24.com/*
// @match *://www.ondemandkorea.com/*
// @match *://onefootball.com/*
// @match *://www.oneplace.com/*
// @match *://eurosport.onet.pl/*
// @match *://film.onet.pl/*
// @match *://moto.onet.pl/*
// @match *://businessinsider.com.pl/*
// @match *://plejada.pl/*
// @match *://onet.tv/*
// @match *://onet100.vod.pl/*
// @match *://www.onionstudios.com/*
// @match *://player.ooyala.com/*
// @match *://oc-video1.ruhr-uni-bochum.de/*
// @match *://oc-video.ruhr-uni-bochum.de/*
// @match *://www.openrec.tv/*
// @match *://www.ora.tv/*
// @match *://www.unsafespeech.com/*
// @match *://fm4.orf.at/*
// @match *://iptv.orf.at/*
// @match *://radiothek.orf.at/*
// @match *://ooe.orf.at/*
// @match *://noe.orf.at/*
// @match *://wien.orf.at/*
// @match *://burgenland.orf.at/*
// @match *://steiermark.orf.at/*
// @match *://kaernten.orf.at/*
// @match *://salzburg.orf.at/*
// @match *://tirol.orf.at/*
// @match *://vorarlberg.orf.at/*
// @match *://oe3.orf.at/*
// @match *://oe1.orf.at/*
// @match *://tvthek.orf.at/*
// @match *://tvonline.osnatel.de/*
// @match *://www.outsidetv.com/*
// @match *://www.packtpub.com/*
// @match *://subscription.packtpub.com/*
// @match *://www.palcomp3.com.br/*
// @match *://www.palcomp3.com/*
// @match *://jp.channel.pandora.tv/*
// @match *://channel.pandora.tv/*
// @match *://www.pandora.tv/*
// @match *://m.pandora.tv/*
// @match *://demo.hosted.panopto.com/*
// @match *://howtovideos.hosted.panopto.com/*
// @match *://unisa.au.panopto.com/*
// @match *://na-training-1.hosted.panopto.com/*
// @match *://ucc.cloud.panopto.eu/*
// @match *://brown.hosted.panopto.com/*
// @match *://utsa.hosted.panopto.com/*
// @match *://www.paramountnetwork.com/*
// @match *://www.paramountplus.com/*
// @match *://parler.com/*
// @match *://parliamentlive.tv/*
// @match *://parlview.aph.gov.au/*
// @match *://www.patreon.com/*
// @match *://www.pbs.org/*
// @match *://player.pbs.org/*
// @match *://watch.knpb.org/*
// @match *://www.pearvideo.com/*
// @match *://peekvids.com/*
// @match *://www.peer.tv/*
// @match *://framatube.org/*
// @match *://peertube2.cpy.re/*
// @match *://peertube.debian.social/*
// @match *://vod.ksite.de/*
// @match *://peertube.tv/*
// @match *://peertube.tux.ovh/*
// @match *://members.onepeloton.com/*
// @match *://www.people.com/*
// @match *://player.performgroup.com/*
// @match *://www.periscope.tv/*
// @match *://philharmoniedeparis.fr/*
// @match *://live.philharmoniedeparis.fr/*
// @match *://otoplayer.philharmoniedeparis.fr/*
// @match *://www.phoenix.de/*
// @match *://media.photobucket.com/*
// @match *://piapro.jp/*
// @match *://picarto.tv/*
// @match *://player.piksel.com/*
// @match *://www.pinkbike.com/*
// @match *://es.pinkbike.org/*
// @match *://www.pinterest.com/*
// @match *://www.pinterest.ca/*
// @match *://co.pinterest.com/*
// @match *://dood.to/*
// @match *://sketch.pixiv.net/*
// @match *://out.pladform.ru/*
// @match *://static.pladform.ru/*
// @match *://video.pladform.ru/*
// @match *://www.planetmarathi.com/*
// @match *://platzi.com/*
// @match *://courses.platzi.com/*
// @match *://www.play.fm/*
// @match *://www.playplus.tv/*
// @match *://play.stuff.co.nz/*
// @match *://plays.tv/*
// @match *://www.playsuisse.ch/*
// @match *://www.playtvak.cz/*
// @match *://slowtv.playtvak.cz/*
// @match *://zpravy.idnes.cz/*
// @match *://www.lidovky.cz/*
// @match *://www.metro.cz/*
// @match *://www.playvid.com/*
// @match *://www.playvids.com/*
// @match *://config.playwire.com/*
// @match *://cdn.playwire.com/*
// @match *://www.pluralsight.com/*
// @match *://app.pluralsight.com/*
// @match *://pluto.tv/*
// @match *://podbay.fm/*
// @match *://www.podchaser.com/*
// @match *://scienceteachingtips.podomatic.com/*
// @match *://ostbahnhof.podomatic.com/*
// @match *://www.podomatic.com/*
// @match *://www.pokemon.com/*
// @match *://watch.pokemon.com/*
// @match *://www.pokergo.com/*
// @match *://polsatgo.pl/*
// @match *://jedynka.polskieradio.pl/*
// @match *://trojka.polskieradio.pl/*
// @match *://www.polskieradio.pl/*
// @match *://radiokierowcow.pl/*
// @match *://polskieradio24.pl/*
// @match *://player.polskieradio.pl/*
// @match *://podcasty.polskieradio.pl/*
// @match *://popcorntimes.tv/*
// @match *://animemanga.popcorntv.it/*
// @match *://cinema.popcorntv.it/*
// @match *://www.porn.com/*
// @match *://se.porn.com/*
// @match *://www.pornerbros.com/*
// @match *://m.pornerbros.com/*
// @match *://pornez.net/*
// @match *://www.pornflip.com/*
// @match *://www.pornhd.com/*
// @match *://www.pornhub.com/*
// @match *://fr.pornhub.com/*
// @match *://www.thumbzilla.com/*
// @match *://www.pornhub.net/*
// @match *://www.pornhub.org/*
// @match *://www.pornhubpremium.com/*
// @match *://pornhubvybmsymdol4iibwgwtkpwmeyd6luq2gxajgjzfjvotyt5zhyd.onion/*
// @match *://de.pornhub.com/*
// @match *://www.pornotube.com/*
// @match *://www.pornovoisines.com/*
// @match *://www.pornoxo.com/*
// @match *://www.porntube.com/*
// @match *://m.porntube.com/*
// @match *://prankcast.com/*
// @match *://www.premiershiprugby.com/*
// @match *://www.presstv.ir/*
// @match *://www.projectveritas.com/*
// @match *://www.prosieben.de/*
// @match *://www.prosiebenmaxx.de/*
// @match *://www.sixx.de/*
// @match *://www.sat1.de/*
// @match *://www.kabeleins.de/*
// @match *://www.ran.de/*
// @match *://www.the-voice-of-germany.de/*
// @match *://www.fem.com/*
// @match *://www.kabeleinsdoku.de/*
// @match *://www.sat1gold.de/*
// @match *://www.galileo.tv/*
// @match *://www.advopedia.de/*
// @match *://beta.prx.org/*
// @match *://listen.prx.org/*
// @match *://puhutv.com/*
// @match *://www.puls4.com/*
// @match *://pyvideo.org/*
// @match *://www.qingting.fm/*
// @match *://m.qtfm.cn/*
// @match *://y.qq.com/*
// @match *://quantum-tv.com/*
// @match *://www.qub.ca/*
// @match *://videos.r7.com/*
// @match *://esportes.r7.com/*
// @match *://noticias.r7.com/*
// @match *://player.r7.com/*
// @match *://tv.r7.com/*
// @match *://radiko.jp/*
// @match *://ndr2.radio.de/*
// @match *://www.radiobremen.de/*
// @match *://ici.radio-canada.ca/*
// @match *://maison.radiofrance.fr/*
// @match *://www.radiojavan.com/*
// @match *://radiokapital.pl/*
// @match *://player.radiozet.pl/*
// @match *://rad.live/*
// @match *://www.raisport.rai.it/*
// @match *://www.rai.it/*
// @match *://www.rainews.it/*
// @match *://www.raiplay.it/*
// @match *://www.raiplaysound.it/*
// @match *://raisudtirol.rai.it/*
// @match *://www.raywenderlich.com/*
// @match *://videos.raywenderlich.com/*
// @match *://www.rbmaradio.com/*
// @match *://video.corriere.it/*
// @match *://viaggi.corriere.it/*
// @match *://video.gazzetta.it/*
// @match *://video.rcs.it/*
// @match *://video.gazzanet.gazzetta.it/*
// @match *://www.leitv.it/*
// @match *://www.youreporter.it/*
// @match *://www.rctiplus.com/*
// @match *://www.rds.ca/*
// @match *://www.redbull.com/*
// @match *://www.redbull.tv/*
// @match *://www.reddit.com/*
// @match *://old.reddit.com/*
// @match *://nm.reddit.com/*
// @match *://www.redditmedia.com/*
// @match *://www.redgifs.com/*
// @match *://thumbs2.redgifs.com/*
// @match *://www.redtube.com/*
// @match *://embed.redtube.com/*
// @match *://it.redtube.com/*
// @match *://www.regio-tv.de/*
// @match *://ren.tv/*
// @match *://www.restudy.dk/*
// @match *://portal.restudy.dk/*
// @match *://www.reuters.com/*
// @match *://www.reverbnation.com/*
// @match *://mediahub.rice.edu/*
// @match *://rmcdecouverte.bfmtv.com/*
// @match *://www.rockstargames.com/*
// @match *://www.rokfin.com/*
// @match *://rokfin.com/*
// @match *://roosterteeth.com/*
// @match *://achievementhunter.roosterteeth.com/*
// @match *://funhaus.roosterteeth.com/*
// @match *://screwattack.roosterteeth.com/*
// @match *://theknow.roosterteeth.com/*
// @match *://www.rottentomatoes.com/*
// @match *://prehravac.rozhlas.cz/*
// @match *://www.rtbf.be/*
// @match *://rtd.rt.com/*
// @match *://www.rte.ie/*
// @match *://rte.ie/*
// @match *://www.rtl.lu/*
// @match *://5minutes.rtl.lu/*
// @match *://today.rtl.lu/*
// @match *://www.rtlxl.nl/*
// @match *://www.rtl.nl/*
// @match *://rtlxl.nl/*
// @match *://static.rtl.nl/*
// @match *://embed.rtl.nl/*
// @match *://www.rtl2.de/*
// @match *://you.rtl2.de/*
// @match *://www.rt.com/*
// @match *://www.rtp.pt/*
// @match *://rtrfm.com.au/*
// @match *://www.rts.ch/*
// @match *://pages.rts.ch/*
// @match *://www.rtve.es/*
// @match *://www.rtvnh.nl/*
// @match *://www.rtvs.sk/*
// @match *://www.rtvslo.si/*
// @match *://365.rtvslo.si/*
// @match *://4d.rtvslo.si/*
// @match *://www.ruhd.ru/*
// @match *://rule34video.com/*
// @match *://rumble.com/*
// @match *://www.rumble.com/*
// @match *://www.ruptly.tv/*
// @match *://rutube.ru/*
// @match *://player.rutv.ru/*
// @match *://player.vgtrk.com/*
// @match *://testplayer.vgtrk.com/*
// @match *://www.ruutu.fi/*
// @match *://www.supla.fi/*
// @match *://static.nelonenmedia.fi/*
// @match *://ruv.is/*
// @match *://www.ruv.is/*
// @match *://www.safaribooksonline.com/*
// @match *://learning.oreilly.com/*
// @match *://www.oreilly.com/*
// @match *://techbus.safaribooksonline.com/*
// @match *://www.saitosan.net/*
// @match *://saktv.ch/*
// @match *://tv.salt.ch/*
// @match *://samplefocus.com/*
// @match *://www.webtv.sangiin.go.jp/*
// @match *://videos.sapo.pt/*
// @match *://v2.videos.sapo.pt/*
// @match *://en.savefrom.net/*
// @match *://www.sbs.com.au/*
// @match *://www.schooltv.nl/*
// @match *://api.screen9.com/*
// @match *://folkhogskolekanalen.screen9.tv/*
// @match *://play.su.se/*
// @match *://www.screencast.com/*
// @match *://screencast.com/*
// @match *://watch.screencastify.com/*
// @match *://screencast-o-matic.com/*
// @match *://www.cookingchanneltv.com/*
// @match *://www.diynetwork.com/*
// @match *://www.foodnetwork.com/*
// @match *://www.travelchannel.com/*
// @match *://www.discovery.com/*
// @match *://watch.geniuskitchen.com/*
// @match *://scrolller.com/*
// @match *://learning.scte.org/*
// @match *://www.seeker.com/*
// @match *://www.help.senate.gov/*
// @match *://www.appropriations.senate.gov/*
// @match *://www.banking.senate.gov/*
// @match *://www.senate.gov/*
// @match *://embed.sendtonews.com/*
// @match *://www.servustv.com/*
// @match *://www.servus.com/*
// @match *://www.pm-wissen.com/*
// @match *://sexu.com/*
// @match *://www.seznamzpravy.cz/*
// @match *://www.seznam.cz/*
// @match *://shahid.mbc.net/*
// @match *://shared.sx/*
// @match *://www.shemaroome.com/*
// @match *://www.showroom-live.com/*
// @match *://www.shugiintv.go.jp/*
// @match *://api.simplecast.com/*
// @match *://player.simplecast.com/*
// @match *://the-re-bind-io-podcast.simplecast.com/*
// @match *://video.sina.com.cn/*
// @match *://skeb.jp/*
// @match *://sport.sky.it/*
// @match *://tg24.sky.it/*
// @match *://news.sky.com/*
// @match *://www.skysports.com/*
// @match *://www.skylinewebcams.com/*
// @match *://www.skynewsarabia.com/*
// @match *://www.skynews.com.au/*
// @match *://www.slideshare.net/*
// @match *://slideslive.com/*
// @match *://www.slutload.com/*
// @match *://mobile.slutload.com/*
// @match *://smotrim.ru/*
// @match *://www.snotr.com/*
// @match *://tv.sohu.com/*
// @match *://my.tv.sohu.com/*
// @match *://www.sonyliv.com/*
// @match *://soundcloud.com/*
// @match *://api.soundcloud.com/*
// @match *://w.soundcloud.com/*
// @match *://soundgasm.net/*
// @match *://southpark.cc.com/*
// @match *://www.southparkstudios.com/*
// @match *://www.southpark.de/*
// @match *://www.southpark.lat/*
// @match *://www.southpark.nl/*
// @match *://www.southparkstudios.dk/*
// @match *://www.southparkstudios.nu/*
// @match *://sovietscloset.com/*
// @match *://spankbang.com/*
// @match *://m.spankbang.com/*
// @match *://www.spankwire.com/*
// @match *://www.spiegel.de/*
// @match *://vod.sport5.co.il/*
// @match *://www.sport5.co.il/*
// @match *://news.sportbox.ru/*
// @match *://sportdeutschland.tv/*
// @match *://api.spreaker.com/*
// @match *://www.spreaker.com/*
// @match *://cms.springboardplatform.com/*
// @match *://www.universalkids.com/*
// @match *://www.sproutonline.com/*
// @match *://sr-mediathek.sr-online.de/*
// @match *://sr-mediathek.de/*
// @match *://www.srf.ch/*
// @match *://www.rtr.ch/*
// @match *://play.swissinfo.ch/*
// @match *://openclassroom.stanford.edu/*
// @match *://intl.startrek.com/*
// @match *://www.startrek.com/*
// @match *://www.startv.com.tr/*
// @match *://store.steampowered.com/*
// @match *://steamcommunity.com/*
// @match *://www.stitcher.com/*
// @match *://storyfire.com/*
// @match *://streamable.com/*
// @match *://streamanity.com/*
// @match *://streamcloud.eu/*
// @match *://www.televizeseznam.cz/*
// @match *://www.stream.cz/*
// @match *://streamff.com/*
// @match *://streetvoice.com/*
// @match *://tw.streetvoice.com/*
// @match *://portal.stretchinternet.com/*
// @match *://stripchat.com/*
// @match *://player.stv.tv/*
// @match *://haleynahman.substack.com/*
// @match *://andrewzimmern.substack.com/*
// @match *://www.sunporno.com/*
// @match *://embeds.sunporno.com/*
// @match *://sverigesradio.se/*
// @match *://www.svt.se/*
// @match *://www.svtplay.se/*
// @match *://www.oppetarkiv.se/*
// @match *://www.swearnet.com/*
// @match *://swrmediathek.de/*
// @match *://www.syfy.com/*
// @match *://24syv.dk/*
// @match *://sztv.hu/*
// @match *://www.t-online.de/*
// @match *://www.tagesschau.de/*
// @match *://tass.ru/*
// @match *://itar-tass.com/*
// @match *://www.tntdrama.com/*
// @match *://www.tbs.com/*
// @match *://tds.lifeway.com/*
// @match *://gns3.teachable.com/*
// @match *://v1.upskillcourses.com/*
// @match *://www.teachertube.com/*
// @match *://www.teachingchannel.org/*
// @match *://teamcoco.com/*
// @match *://conan25.teamcoco.com/*
// @match *://teamtreehouse.com/*
// @match *://techtalks.tv/*
// @match *://techtv.mit.edu/*
// @match *://embed.ted.com/*
// @match *://www.ted.com/*
// @match *://www.t13.cl/*
// @match *://www.tele5.de/*
// @match *://tele5.de/*
// @match *://bx1.be/*
// @match *://www.telecinco.es/*
// @match *://www.cuatro.com/*
// @match *://www.mediaset.es/*
// @match *://www.telegraaf.nl/*
// @match *://t.me/*
// @match *://www.telemb.be/*
// @match *://telemb.be/*
// @match *://www.telemundo.com/*
// @match *://zonevideo.telequebec.tv/*
// @match *://coucou.telequebec.tv/*
// @match *://lindicemcsween.telequebec.tv/*
// @match *://bancpublic.telequebec.tv/*
// @match *://www.telequebec.tv/*
// @match *://squat.telequebec.tv/*
// @match *://video.telequebec.tv/*
// @match *://www.tele-task.de/*
// @match *://www.telewebion.com/*
// @match *://video.tempo.co/*
// @match *://www.tennistv.com/*
// @match *://10play.com.au/*
// @match *://www.tf1.fr/*
// @match *://www.tfo.org/*
// @match *://the-hole.tv/*
// @match *://theintercept.com/*
// @match *://feed.theplatform.com/*
// @match *://www.thestar.com/*
// @match *://www.thesun.co.uk/*
// @match *://www.theta.tv/*
// @match *://weather.com/*
// @match *://www.thisamericanlife.org/*
// @match *://www.thisav.com/*
// @match *://www.thisoldhouse.com/*
// @match *://thisvid.com/*
// @match *://3speak.tv/*
// @match *://www.tiktok.com/*
// @match *://tiktok.com/*
// @match *://tinypic.com/*
// @match *://de.tinypic.com/*
// @match *://go.tlc.com/*
// @match *://www.tmz.com/*
// @match *://www.tnaflix.com/*
// @match *://player.tnaflix.com/*
// @match *://player.empflix.com/*
// @match *://video.toggle.sg/*
// @match *://www.toggo.de/*
// @match *://tokentube.net/*
// @match *://audycje.tokfm.pl/*
// @match *://www.toongoggles.com/*
// @match *://ici.tou.tv/*
// @match *://videos.toypics.net/*
// @match *://www.traileraddict.com/*
// @match *://watch.travelchannel.com/*
// @match *://triller.co/*
// @match *://www.trilulilu.ro/*
// @match *://trovo.live/*
// @match *://www.trtcocuk.net.tr/*
// @match *://trueid.id/*
// @match *://vn.trueid.net/*
// @match *://trueid.ph/*
// @match *://www.trunews.com/*
// @match *://truthsocial.com/*
// @match *://www.trutv.com/*
// @match *://www.tube8.com/*
// @match *://tube.tugraz.at/*
// @match *://tubitv.com/*
// @match *://tatianamaslanydaily.tumblr.com/*
// @match *://maskofthedragon.tumblr.com/*
// @match *://shieldfoss.tumblr.com/*
// @match *://jujanon.tumblr.com/*
// @match *://bartlebyshop.tumblr.com/*
// @match *://afloweroutofstone.tumblr.com/*
// @match *://naked-yogi.tumblr.com/*
// @match *://prozdvoices.tumblr.com/*
// @match *://dominustempori.tumblr.com/*
// @match *://sutiblr.tumblr.com/*
// @match *://silami.tumblr.com/*
// @match *://tunein.com/*
// @match *://tun.in/*
// @match *://tune.pk/*
// @match *://embed.tune.pk/*
// @match *://www.turbo.fr/*
// @match *://tv.dfb.de/*
// @match *://www.tv2.no/*
// @match *://www.tvsyd.dk/*
// @match *://www.tv2lorry.dk/*
// @match *://www.tv2ostjylland.dk/*
// @match *://www.tvmidtvest.dk/*
// @match *://www.tv2fyn.dk/*
// @match *://www.tv2east.dk/*
// @match *://www.tv2nord.dk/*
// @match *://play.tv2bornholm.dk/*
// @match *://tv2play.hu/*
// @match *://www.tv4.se/*
// @match *://www.tv4play.se/*
// @match *://revoir.tv5monde.com/*
// @match *://www.tv5unis.ca/*
// @match *://www.tv8.it/*
// @match *://videos.tva.ca/*
// @match *://video.tva.ca/*
// @match *://www.tvanouvelles.ca/*
// @match *://www.tvc.ru/*
// @match *://tver.jp/*
// @match *://www.tvigle.ru/*
// @match *://cloud.tvigle.ru/*
// @match *://tviplayer.iol.pt/*
// @match *://www.tvland.com/*
// @match *://www.tvn24.pl/*
// @match *://tvnmeteo.tvn24.pl/*
// @match *://fakty.tvn24.pl/*
// @match *://sport.tvn24.pl/*
// @match *://tvn24bis.pl/*
// @match *://de.tvnet.gov.vn/*
// @match *://vn.tvnet.gov.vn/*
// @match *://us.tvnet.gov.vn/*
// @match *://www.tvnoe.cz/*
// @match *://www.tvnow.de/*
// @match *://cdn.ethnos.gr/*
// @match *://www.ethnos.gr/*
// @match *://www.tvopen.gr/*
// @match *://swipeto.pl/*
// @match *://www.tvp.pl/*
// @match *://wiadomosci.tvp.pl/*
// @match *://warszawa.tvp.pl/*
// @match *://www.tvp.info/*
// @match *://opole.tvp.pl/*
// @match *://abc.tvp.pl/*
// @match *://jp2.tvp.pl/*
// @match *://vod.tvp.pl/*
// @match *://krakow.tvp.pl/*
// @match *://teleexpress.tvp.pl/*
// @match *://sport.tvp.pl/*
// @match *://tvp.info/*
// @match *://www.tvpparlament.pl/*
// @match *://tvpworld.com/*
// @match *://tvpstream.vod.tvp.pl/*
// @match *://tvplayer.com/*
// @match *://tv3play.skaties.lv/*
// @match *://play.tv3.ee/*
// @match *://tweakers.net/*
// @match *://twitcasting.tv/*
// @match *://clips.twitch.tv/*
// @match *://www.twitch.tv/*
// @match *://m.twitch.tv/*
// @match *://go.twitch.tv/*
// @match *://player.twitch.tv/*
// @match *://twitter.com/*
// @match *://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion/*
// @match *://amp.twimg.com/*
// @match *://www.udemy.com/*
// @match *://wipro.udemy.com/*
// @match *://video.udn.com/*
// @match *://www.ukcolumn.org/*
// @match *://uktvplay.uktv.co.uk/*
// @match *://uktvplay.co.uk/*
// @match *://www.universal-music.de/*
// @match *://utv.unistra.fr/*
// @match *://unity3d.com/*
// @match *://www.unscripted.news/*
// @match *://player.mais.uol.com.br/*
// @match *://tvuol.uol.com.br/*
// @match *://mais.uol.com.br/*
// @match *://noticias.band.uol.com.br/*
// @match *://videos.band.uol.com.br/*
// @match *://noticias.uol.com.br/*
// @match *://content.uplynk.com/*
// @match *://urort.p3.no/*
// @match *://urplay.se/*
// @match *://urskola.se/*
// @match *://www.usanetwork.com/*
// @match *://www.usatoday.com/*
// @match *://www.ustream.tv/*
// @match *://video.ibm.com/*
// @match *://ustudio.com/*
// @match *://app.ustudio.com/*
// @match *://utreon.com/*
// @match *://video.varzesh3.com/*
// @match *://vbox7.com/*
// @match *://i49.vbox7.com/*
// @match *://veehd.com/*
// @match *://app.veo.co/*
// @match *://www.veoh.com/*
// @match *://www.vesti.ru/*
// @match *://hitech.vesti.ru/*
// @match *://sochi2014.vesti.ru/*
// @match *://www.vevo.com/*
// @match *://embed.vevo.com/*
// @match *://tv.vevo.com/*
// @match *://www.vgtv.no/*
// @match *://www.aftenposten.no/*
// @match *://tv.vg.no/*
// @match *://ap.vgtv.no/*
// @match *://tv.aftonbladet.se/*
// @match *://www.aftonbladet.se/*
// @match *://www.vh1.com/*
// @match *://www.viafree.no/*
// @match *://www.viafree.dk/*
// @match *://www.viafree.se/*
// @match *://www.viafree.fi/*
// @match *://video.vice.com/*
// @match *://vms.vice.com/*
// @match *://www.viceland.com/*
// @match *://www.vice.com/*
// @match *://www.vicetv.com/*
// @match *://www.vidbit.co/*
// @match *://www.viddler.com/*
// @match *://videa.hu/*
// @match *://videakid.hu/*
// @match *://video.arnes.si/*
// @match *://video.sky.it/*
// @match *://xfactor.sky.it/*
// @match *://masterchef.sky.it/*
// @match *://www.videodetective.com/*
// @match *://www.videofy.me/*
// @match *://videos.neurips.cc/*
// @match *://videos.icts.res.in/*
// @match *://videos.cncf.io/*
// @match *://player.videoken.com/*
// @match *://videomore.ru/*
// @match *://player.videomore.ru/*
// @match *://odysseus.more.tv/*
// @match *://siren.more.tv/*
// @match *://more.tv/*
// @match *://videopress.com/*
// @match *://video.wordpress.com/*
// @match *://www.vidio.com/*
// @match *://www.vidlii.com/*
// @match *://www.snagfilms.com/*
// @match *://main.snagfilms.com/*
// @match *://www.winnersview.com/*
// @match *://www.monumentalsportsnetwork.com/*
// @match *://www.marquee.tv/*
// @match *://www.hoichoi.tv/*
// @match *://embed.snagfilms.com/*
// @match *://videolectures.net/*
// @match *://www.viki.com/*
// @match *://vimeo.com/*
// @match *://player.vimeo.com/*
// @match *://vimeopro.com/*
// @match *://www.vimm.tv/*
// @match *://videocampus.sachsen.de/*
// @match *://www2.univ-sba.dz/*
// @match *://vimp.weka-fachmedien.de/*
// @match *://vimp.oth-regensburg.de/*
// @match *://www.fh-bielefeld.de/*
// @match *://vimple.ru/*
// @match *://player.vimple.ru/*
// @match *://vimple.co/*
// @match *://vine.co/*
// @match *://cdn.viqeo.tv/*
// @match *://api.viqeo.tv/*
// @match *://www.viu.com/*
// @match *://india.viu.com/*
// @match *://vivo.sx/*
// @match *://vivo.st/*
// @match *://vk.com/*
// @match *://m.vk.com/*
// @match *://new.vk.com/*
// @match *://www.vlive.tv/*
// @match *://channels.vlive.tv/*
// @match *://vm.tiktok.com/*
// @match *://vt.tiktok.com/*
// @match *://vodlocker.com/*
// @match *://vod.pl/*
// @match *://vod-platform.net/*
// @match *://embed.kwikmotion.com/*
// @match *://voicerepublic.com/*
// @match *://voicy.jp/*
// @match *://volej.tv/*
// @match *://www.voot.com/*
// @match *://www.theverge.com/*
// @match *://www.vox.com/*
// @match *://www.sbnation.com/*
// @match *://www.recode.net/*
// @match *://tegenlicht.vpro.nl/*
// @match *://www.vpro.nl/*
// @match *://www.2doc.nl/*
// @match *://v.qq.com/*
// @match *://www.vrak.tv/*
// @match *://www.vrt.be/*
// @match *://sporza.be/*
// @match *://vrv.co/*
// @match *://vshare.io/*
// @match *://vtm.be/*
// @match *://vtxtv.ch/*
// @match *://m.vuclip.com/*
// @match *://vupload.com/*
// @match *://www.vvvvid.it/*
// @match *://vybory.mos.ru/*
// @match *://vzaar.com/*
// @match *://view.vzaar.com/*
// @match *://www.wakanim.tv/*
// @match *://vod.walla.co.il/*
// @match *://player.waly.tv/*
// @match *://wasd.tv/*
// @match *://www.washingtonpost.com/*
// @match *://www.wat.tv/*
// @match *://www.watchbox.de/*
// @match *://www.watchindianporn.net/*
// @match *://deviceids-medp.wdr.de/*
// @match *://mobile-ondemand.wdr.de/*
// @match *://www.wdrmaus.de/*
// @match *://www1.wdr.de/*
// @match *://www.sportschau.de/*
// @match *://kinder.wdr.de/*
// @match *://web.archive.org/*
// @match *://warszawa-plac-zamkowy.webcamera.pl/*
// @match *://gdansk-stare-miasto.webcamera.pl/*
// @match *://bl.webcaster.pro/*
// @match *://www.webofstories.com/*
// @match *://weibo.com/*
// @match *://m.weibo.cn/*
// @match *://www.weiqitv.com/*
// @match *://wetv.vip/*
// @match *://whowatch.tv/*
// @match *://commons.wikimedia.org/*
// @match *://willow.tv/*
// @match *://platform.wim.tv/*
// @match *://www.winsports.co/*
// @match *://fast.wistia.net/*
// @match *://fast.wistia.com/*
// @match *://www.worldstarhiphop.com/*
// @match *://m.worldstarhiphop.com/*
// @match *://pilot.wp.pl/*
// @match *://video-api.wsj.com/*
// @match *://www.wsj.com/*
// @match *://www.barrons.com/*
// @match *://www.wwe.com/*
// @match *://de.wwe.com/*
// @match *://wyborcza.pl/*
// @match *://www.wysokieobcasy.pl/*
// @match *://xbef.com/*
// @match *://xboxclips.com/*
// @match *://gameclips.io/*
// @match *://uqload.com/*
// @match *://xvideosharing.com/*
// @match *://aparat.cam/*
// @match *://wolfstream.tv/*
// @match *://xhamster.com/*
// @match *://m.xhamster.com/*
// @match *://it.xhamster.com/*
// @match *://pt.xhamster.com/*
// @match *://xhamster.one/*
// @match *://xhamster.desi/*
// @match *://xhamster2.com/*
// @match *://xhamster11.com/*
// @match *://xhamster26.com/*
// @match *://de.xhamster.com/*
// @match *://xhday.com/*
// @match *://www.ximalaya.com/*
// @match *://m.ximalaya.com/*
// @match *://www.xinpianchang.com/*
// @match *://x-minus.org/*
// @match *://www.xnxx.com/*
// @match *://video.xnxx.com/*
// @match *://www.xnxx3.com/*
// @match *://frontend.xstream.dk/*
// @match *://www.xtube.com/*
// @match *://vlog.xuite.net/*
// @match *://www.xvideos.com/*
// @match *://flashservice.xvideos.com/*
// @match *://static-hw.xvideos.com/*
// @match *://xvideos.com/*
// @match *://xvideos.es/*
// @match *://www.xvideos.es/*
// @match *://fr.xvideos.com/*
// @match *://it.xvideos.com/*
// @match *://de.xvideos.com/*
// @match *://xxxymovies.com/*
// @match *://screen.yahoo.com/*
// @match *://uk.screen.yahoo.com/*
// @match *://news.yahoo.com/*
// @match *://www.yahoo.com/*
// @match *://gma.yahoo.com/*
// @match *://sports.yahoo.com/*
// @match *://tw.news.yahoo.com/*
// @match *://tw.video.yahoo.com/*
// @match *://malaysia.news.yahoo.com/*
// @match *://es-us.noticias.yahoo.com/*
// @match *://gyao.yahoo.co.jp/*
// @match *://streaming.yahoo.co.jp/*
// @match *://news.yahoo.co.jp/*
// @match *://yadi.sk/*
// @match *://music.yandex.ru/*
// @match *://music.yandex.com/*
// @match *://yandex.ru/*
// @match *://frontend.vh.yandex.ru/*
// @match *://yandex.com/*
// @match *://www.yapfiles.ru/*
// @match *://api.yapfiles.ru/*
// @match *://www.yesjapan.com/*
// @match *://v.yinyuetai.com/*
// @match *://areena.yle.fi/*
// @match *://hot.ynet.co.il/*
// @match *://www.youjizz.com/*
// @match *://v.youku.com/*
// @match *://player.youku.com/*
// @match *://list.youku.com/*
// @match *://www.younow.com/*
// @match *://www.youporn.com/*
// @match *://sxyprn.com/*
// @match *://yourupload.com/*
// @match *://www.yourupload.com/*
// @match *://embed.yourupload.com/*
// @match *://www.youtube.com/*
// @match *://youtube.com/*
// @match *://vid.plus/*
// @match *://zwearz.com/*
// @match *://invidio.us/*
// @match *://redirect.invidious.io/*
// @match *://music.youtube.com/*
// @match *://www.youtubekids.com/*
// @match *://youtu.be/*
// @match *://www.zapiks.fr/*
// @match *://www.zapiks.com/*
// @match *://zattoo.com/*
// @match *://www.zdf.de/*
// @match *://www.zee5.com/*
// @match *://zeenews.india.com/*
// @match *://zen.yandex.ru/*
// @match *://dzen.ru/*
// @match *://www.zhihu.com/*
// @match *://mp3.zing.vn/*
// @match *://zingmp3.vn/*
// @match *://economist.zoom.us/*
// @match *://player.zype.com/*
// @match *://media.w3.org/*
// @match *://calimero.tk/*
// @match *://ai-radio.org:8000/*
// @match *://ftp.nluug.nl/*
// @match *://phihag.de/*
// @match *://podcastfeeds.nbcnews.com/*
// @match *://anchor.fm/*
// @match *://www.hellointernet.fm/*
// @match *://www.omnycontent.com/*
// @match *://metafilegenerator.de/*
// @match *://services.media.howstuffworks.com/*
// @match *://api.new.livestream.com/*
// @match *://yt-dash-mse-test.commondatastorage.googleapis.com/*
// @match *://once.unicornmedia.com/*
// @match *://www.nacentapps.com/*
// @match *://www.google.com/*
// @match *://www.hodiho.fr/*
// @match *://bronyrock.com/*
// @match *://www.rollingstone.com/*
// @match *://www.macrumors.com/*
// @match *://wnep.com/*
// @match *://www.tested.com/*
// @match *://www.theguardian.com/*
// @match *://www.rg.ru/*
// @match *://sch1298sz.mskobr.ru/*
// @match *://www.vestifinance.ru/*
// @match *://www.kinomyvi.tv/*
// @match *://www.numisc.com/*
// @match *://en.support.wordpress.com/*
// @match *://www.waoanime.tv/*
// @match *://www.tv-replay.fr/*
// @match *://www.tsprod.com/*
// @match *://www.wired.com/*
// @match *://www.spi0n.com/*
// @match *://www.bumm.sk/*
// @match *://www.badzine.de/*
// @match *://www.vulture.com/*
// @match *://play.google.com/*
// @match *://www.handjobhub.com/*
// @match *://umpire-empire.com/*
// @match *://www.getdrip.com/*
// @match *://nakedsecurity.sophos.com/*
// @match *://www.guitarplayer.com/*
// @match *://radiocnrv.com/*
// @match *://www.esa.int/*
// @match *://skiplagged.com/*
// @match *://undergroundwellness.com/*
// @match *://deadspin.com/*
// @match *://thedailyshow.cc.com/*
// @match *://media.nationalarchives.gov.uk/*
// @match *://www.suffolk.edu/*
// @match *://www.hollywoodreporter.com/*
// @match *://www.indiedb.com/*
// @match *://www.txxx.com/*
// @match *://ortcam.com/*
// @match *://www.vooplayer.com/*
// @match *://www.rtlnieuws.nl/*
// @match *://www.skipass.com/*
// @match *://www.premierchristianradio.com/*
// @match *://fod.infobase.com/*
// @match *://www.cornell.edu/*
// @match *://www.gsd.harvard.edu/*
// @match *://www.cns.nyu.edu/*
// @match *://thechive.com/*
// @match *://tvrain.ru/*
// @match *://muz-tv.ru/*
// @match *://www.cinemablend.com/*
// @match *://crooksandliars.com/*
// @match *://theothermccain.com/*
// @match *://www.riderfans.com/*
// @match *://www.clickhole.com/*
// @match *://whilewewatch.blogspot.ru/*
// @match *://helpx.adobe.com/*
// @match *://www.hudl.com/*
// @match *://www.rtl.be/*
// @match *://www.theatlantic.com/*
// @match *://www.hostblogger.de/*
// @match *://5pillarsuk.com/*
// @match *://www.lothype.com/*
// @match *://www.expansion.com/*
// @match *://www.quartier-rouge.be/*
// @match *://openclassrooms.com/*
// @match *://racing4everyone.eu/*
// @match *://support.arkena.com/*
// @match *://nova.bg/*
// @match *://forum.dvdtalk.com/*
// @match *://magazzino.friday.ru/*
// @match *://www.skai.gr/*
// @match *://www.in.gr/*
// @match *://www.ertnews.gr/*
// @match *://www.golfchannel.com/*
// @match *://www.hsgac.senate.gov/*
// @match *://www.sedona.com/*
// @match *://tv5.ca/*
// @match *://kron4.com/*
// @match *://www.vanityfair.com/*
// @match *://www.noviny.sk/*
// @match *://help.vzaar.com/*
// @match *://www.paragon-software.com/*
// @match *://youtube-dl-demo.neocities.org/*
// @match *://www.heidelberg-laureate-forum.org/*
// @match *://www.kidzworld.com/*
// @match *://www.cloudflare.com/*
// @match *://joinpeertube.org/*
// @match *://streetkitchen.hu/*
// @match *://www.vol.at/*
// @match *://share-videos.se/*
// @match *://viqeo.tv/*
// @match *://video.sibnet.ru/*
// @match *://www.beinsports.com/*
// @match *://blog.tomeuvizoso.net/*
// @match *://demo.vhx.tv/*
// @match *://www.adn.com/*
// @match *://www.demorgen.be/*
// @match *://www.bio.org/*
// @match *://www.msmotor.tv/*
// @match *://www.kvs-demo.com/*
// @match *://youix.com/*
// @match *://bogmedia.org/*
// @match *://www.camhub.world/*
// @match *://v.redd.it/*
// @match *://www.lactv.it/*
// @match *://www.gezip.net/*
// @match *://kkzz.kr/*
// @match *://www.monash.edu/*
// @match *://www.nelonen.fi/*
// @match *://www.hs.fi/*
// @match *://www.filmarkivet.se/*
// @match *://www.mollymovieclub.com/*
// @match *://www.blockedandreported.org/*
// @match *://www.skimag.com/*
// @match *://www.nu.nl/*
// @match *://www.autoweek.nl/*
// @match *://www.extra.cz/*
// @match *://shooshtime.com/*
// ==/UserScript==

const style = document.createElement('style');
style.innerHTML = `
@keyframes slide-left {
  from {
    right: -80px;
  }

  to {
    right: 0;
  }
}

@keyframes slide-right {
  from {
    right: 0;
  }

  to {
    right: -80px;
  }
}

.play-button {
  animation: 0.5s ease-in 0.3s slide-right forwards;
  background: linear-gradient(to right, #7f7fd5, #86a8e7, #91eae4);
  border-color: rgba(0, 0, 0, 0.2);
  color: #f1f2f3;
  cursor: pointer;
  font-family: Arial;
  font-size: 18px;
  position: fixed;
  top: 8vh;
  right: 0;
  z-index: 99999;
}

.play-button:hover {
  animation: 0.5s ease-in slide-left forwards;
}
`;

const playButton = document.createElement('button');
playButton.classList.add('play-button');
playButton.textContent = '▶ WebPlay';
playButton.title = 'Double click to hide';
playButton.addEventListener('click', () => {
  clearTimeout(Number(playButton.dataset.timer));
  playButton.dataset.timer = setTimeout(() => {
    delete playButton.dataset.timer;
    const params = new URLSearchParams();
    const video = document.querySelector('video');
    params.append('url', window.location.href);
    params.append('parse', 1);
    if (video !== null) {
      params.append('start', video.currentTime);
    }
    const url = 'webplay:?' + params.toString();
    location.assign(url);
    video.pause();
  }, 250);
});
playButton.addEventListener('dblclick', () => {
  clearTimeout(Number(playButton.dataset.timer));
  playButton.remove();
});

const container = document.createElement('div');
container.id = 'webplay-ytdl-' + Number.parseInt(Math.random() * 100);

const shadow = container.attachShadow({ mode: 'closed' });
shadow.append(style);
shadow.append(playButton);

document.body.append(container);

document.addEventListener('fullscreenchange', () => {
  playButton.style.opacity = document.fullscreenElement ? '0' : '1';
});
